/*
 * AutoFrame.java
 *
 * Created on 26 de marzo de 2008, 02:30 AM
 */

package sistema_de_diagnostico.rule;

import javax.swing.JOptionPane;

/**
 *
 * 
 */
public class AutoFrame extends javax.swing.JInternalFrame {
    String tipoV, probaDiabetes, sexo, nivelGlucemia, 
            edad, aumentoApetito, fatigas,
            vomitos, miccionFrecuiente, sed,
            visionBorrosa, infecciones, pierdePeso,
            menosMenstrua, partoPrevio, bebeMalformado,
            colesterolAlto, obesidad, presionAlta,
            embarazada, tipoDiabetes;
    
    BaseReglas objBR=new BaseReglas();
    /** Creates new form AutoFrame */
    public AutoFrame(String TipoV) {
        tipoV=TipoV;
        initComponents();
        jLabel2.setText(tipoV);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCBSize = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Diagnóstico");

        jLabel1.setText("Tipo Diabetes:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("jLabel2");

        jLabel3.setText("¿Aumento de apetito?");

        jCBSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Si", "No" }));
        jCBSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBSizeActionPerformed(evt);
            }
        });

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addComponent(jCBSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCBSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        aumentoApetito=String.valueOf(jCBSize.getSelectedItem());
        
        
        
        probaDiabetes=objBR.getProbaDiabetes(sexo, nivelGlucemia, 
            edad, aumentoApetito, fatigas,
            vomitos, miccionFrecuiente, sed,
            visionBorrosa, infecciones, pierdePeso,
            menosMenstrua, partoPrevio, bebeMalformado,
            colesterolAlto, obesidad, presionAlta,
            embarazada, tipoDiabetes);
        
        // INITIAL VALUE
        
        //  sexo = "x";
        //  nivelGlucemia = "x";
        //  edad = "x";
        //  aumentoApetito = "x";
            fatigas = "x";
            vomitos = "x";
            miccionFrecuiente = "x";
            sed = "x";
            visionBorrosa = "x";
            infecciones = "x";
            pierdePeso = "x";
            menosMenstrua = "x";
            partoPrevio = "x";
            bebeMalformado = "x";
            colesterolAlto = "x";
            obesidad = "x";
            presionAlta = "x";
            embarazada = "x";
            tipoDiabetes = "x";
        
        
        
           if (probaDiabetes==null)
        {
            JOptionPane.showMessageDialog(this, "Verifica las entradas",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Resultado ----> " + probaDiabetes);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCBSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBSizeActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jCBSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
    
}
