/*
 * TipoVFrame.java
 *
 * Created on 25 de marzo de 2008, 08:20 AM
 */
package sistema_de_diagnostico.rule;

import javax.swing.JOptionPane;

/**
 *  Index form
 * 
 */
public class TipoVFrame extends javax.swing.JInternalFrame
{

    Principal objP;
    String fSexo, fGlucemia, fEdad, fEmbarazada;
    String tipoV="";
    /*
    String Numr, Motor;
    String tipoV="";
    */

    /** Creates new form TipoVFrame */
    public TipoVFrame(Principal objP)
    {
        this.objP = objP;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MotorGrup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BAcep = new javax.swing.JButton();
        BCancel = new javax.swing.JButton();
        jRBMotorSi = new javax.swing.JRadioButton();
        jRBMotorNo = new javax.swing.JRadioButton();
        jCBNumR = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Preguntas");
        setToolTipText("");

        jLabel1.setText("Sexo");

        jLabel2.setText("¿Embarazada?");

        BAcep.setText("Aceptar");
        BAcep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAcepActionPerformed(evt);
            }
        });

        BCancel.setText("Cancelar");
        BCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelActionPerformed(evt);
            }
        });

        MotorGrup.add(jRBMotorSi);
        jRBMotorSi.setText("Si");
        jRBMotorSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBMotorSiActionPerformed(evt);
            }
        });

        MotorGrup.add(jRBMotorNo);
        jRBMotorNo.setSelected(true);
        jRBMotorNo.setText("No");
        jRBMotorNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBMotorNoActionPerformed(evt);
            }
        });

        jCBNumR.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "masculino", "femenino" }));
        jCBNumR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBNumRActionPerformed(evt);
            }
        });

        jLabel3.setText("Edad");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Nivel de Glucemia");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BAcep)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(BCancel))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCBNumR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRBMotorSi)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRBMotorNo)))))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jCBNumR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRBMotorSi)
                    .addComponent(jRBMotorNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BAcep)
                    .addComponent(BCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void jRBMotorSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBMotorSiActionPerformed
        // TODO add your handling code here:
        // Embarazada o no
        if (jRBMotorSi.isSelected())
        {
            jRBMotorNo.setSelected(false);
            fEmbarazada = "si";
        }
}//GEN-LAST:event_jRBMotorSiActionPerformed

    private void jRBMotorNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBMotorNoActionPerformed
        // TODO add your handling code here:
        if (jRBMotorNo.isSelected())
        {
            jRBMotorSi.setSelected(false);
            fEmbarazada = "no";
        }
    }//GEN-LAST:event_jRBMotorNoActionPerformed

    private void BCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_BCancelActionPerformed

    private void BAcepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAcepActionPerformed
        // TODO add your handling code here:
        //Get textboxes
        fEdad = String.valueOf(jTextField1);
        fGlucemia = String.valueOf(jTextField2);
        //Get from combo
        fSexo = String.valueOf(jCBNumR.getSelectedItem());
        tipoV = objP.objBR.getTipoDiabetes(fSexo, fGlucemia, fEdad, fEmbarazada);
        System.out.println("Resultado ----> " + tipoV);
        if (tipoV==null)
        {
            JOptionPane.showMessageDialog(this, "Verifica las entradas",
            "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Resultado ----> " + tipoV);
            objP.lanzaFrame(tipoV);
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_BAcepActionPerformed

    private void jCBNumRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBNumRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBNumRActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAcep;
    private javax.swing.JButton BCancel;
    private javax.swing.ButtonGroup MotorGrup;
    private javax.swing.JComboBox jCBNumR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRBMotorNo;
    private javax.swing.JRadioButton jRBMotorSi;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
