/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Pantalla_Principal.java
 *
 * Created on 30/03/2011, 04:34:59 PM
 */

package sistema_de_diagnostico;

import java.util.Vector;

/**
 *
 * @author Karina
 */
public class Pantalla_Principal extends javax.swing.JFrame {

    /** Creates new form Pantalla_Principal */
    public Pantalla_Principal() {
        initComponents();
        setExtendedState(this.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
    }
    public static Vector <Integer> matriz;
    public static Metodos objeto;
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    /*
     *              metodos
     *
     */

     public void obtenerDatos(){
         matriz=  new Vector <Integer>();
        if (t1.isSelected()){
            matriz.add(1);
        } if (t2.isSelected()){
            matriz.add(2);
        } if (t3.isSelected()){
            matriz.add(3);
        } if (t4.isSelected()){
            matriz.add(4);
        } if (t4.isSelected()){
            matriz.add(4);
        } if (t5.isSelected()){
            matriz.add(5);
        } if (t6.isSelected()){
            matriz.add(6);
        } if (t7.isSelected()){
            matriz.add(7);
        } if (t8.isSelected()){
            matriz.add(8);
        } if (t9.isSelected()){
            matriz.add(9);
        } if (t10.isSelected()){
            matriz.add(10);
        } if (t11.isSelected()){
            matriz.add(11);
        }if (t12.isSelected()){
            matriz.add(12);
        }if (t13.isSelected()){
            matriz.add(13);
        }if (t14.isSelected()){
            matriz.add(14);
        }if (t15.isSelected()){
            matriz.add(15);
        }if (t16.isSelected()){
            matriz.add(16);
        }if (t17.isSelected()){
            matriz.add(17);
        }if (t18.isSelected()){
            matriz.add(18);
        }

    }


    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        panelImage2 = new org.edisoncor.gui.panel.PanelImage();
        jLabel2 = new javax.swing.JLabel();
        t1 = new javax.swing.JRadioButton();
        t2 = new javax.swing.JRadioButton();
        t3 = new javax.swing.JRadioButton();
        t4 = new javax.swing.JRadioButton();
        t5 = new javax.swing.JRadioButton();
        t6 = new javax.swing.JRadioButton();
        t7 = new javax.swing.JRadioButton();
        t8 = new javax.swing.JRadioButton();
        t9 = new javax.swing.JRadioButton();
        t10 = new javax.swing.JRadioButton();
        t11 = new javax.swing.JRadioButton();
        t12 = new javax.swing.JRadioButton();
        t13 = new javax.swing.JRadioButton();
        t14 = new javax.swing.JRadioButton();
        t15 = new javax.swing.JRadioButton();
        t16 = new javax.swing.JRadioButton();
        t17 = new javax.swing.JRadioButton();
        t18 = new javax.swing.JRadioButton();
        buttonRound1 = new org.edisoncor.gui.button.ButtonRound();
        buttonRound2 = new org.edisoncor.gui.button.ButtonRound();
        buttonSalir = new org.edisoncor.gui.button.ButtonIcon();
        buttonIcon1 = new org.edisoncor.gui.button.ButtonIcon();
        buttonIcon2 = new org.edisoncor.gui.button.ButtonIcon();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(300);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SITEMA DE DIAGNOSTICO");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
        panelImage1.setLayout(panelImage1Layout);
        panelImage1Layout.setHorizontalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage1Layout.createSequentialGroup()
                .addGroup(panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(panelImage1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelImage1Layout.setVerticalGroup(
            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImage1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(320, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(panelImage1);

        panelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/íconos/K.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("POR FAVOR SELECCIONE LOS SINTOMAS QUE TIENE: ");

        t1.setBackground(new java.awt.Color(255, 255, 0));
        t1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t1.setText("TOS");
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });

        t2.setBackground(new java.awt.Color(255, 255, 0));
        t2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t2.setText("TOS con flema");
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });

        t3.setBackground(new java.awt.Color(255, 255, 0));
        t3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t3.setText("TOs constante y fuerte");
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });

        t4.setBackground(new java.awt.Color(255, 255, 0));
        t4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t4.setText("TOS con sangre");
        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });

        t5.setBackground(new java.awt.Color(255, 255, 0));
        t5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t5.setText("Fiebre");

        t6.setBackground(new java.awt.Color(255, 255, 0));
        t6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t6.setText("Dolor de cabeza");

        t7.setBackground(new java.awt.Color(255, 255, 0));
        t7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t7.setText("Dolor de garganta");

        t8.setBackground(new java.awt.Color(255, 255, 0));
        t8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t8.setText("Dolor del cuerpo");

        t9.setBackground(new java.awt.Color(255, 255, 0));
        t9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t9.setText("Vomito y dearrea");

        t10.setBackground(new java.awt.Color(255, 255, 0));
        t10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t10.setText("Escalofrios");

        t11.setBackground(new java.awt.Color(255, 255, 0));
        t11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t11.setText("Dificultades al respirar");

        t12.setBackground(new java.awt.Color(255, 255, 0));
        t12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t12.setText("Bajar de peso");

        t13.setBackground(new java.awt.Color(255, 255, 0));
        t13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t13.setText("Sudores Nocturnos");

        t14.setBackground(new java.awt.Color(255, 255, 0));
        t14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t14.setText("Dolor en el pecho");

        t15.setBackground(new java.awt.Color(255, 255, 0));
        t15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t15.setText("Inflamacion en el cuello");

        t16.setBackground(new java.awt.Color(255, 255, 0));
        t16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t16.setText("Perdida del apetito");

        t17.setBackground(new java.awt.Color(255, 255, 0));
        t17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t17.setText("Dilatacion del torax");

        t18.setBackground(new java.awt.Color(255, 255, 0));
        t18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t18.setText("Insuficiencia Cardiaca");

        buttonRound1.setBackground(new java.awt.Color(255, 153, 153));
        buttonRound1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/íconos/button_ok.png"))); // NOI18N
        buttonRound1.setText("Diagnosticar");
        buttonRound1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRound1ActionPerformed(evt);
            }
        });

        buttonRound2.setBackground(new java.awt.Color(255, 153, 153));
        buttonRound2.setText("Nuevo");
        buttonRound2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRound2ActionPerformed(evt);
            }
        });

        buttonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/íconos/button_cancel.png"))); // NOI18N
        buttonSalir.setMnemonic('S');
        buttonSalir.setText("SALIR");
        buttonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalirActionPerformed(evt);
            }
        });

        buttonIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/íconos/AYUDA.png"))); // NOI18N
        buttonIcon1.setText("buttonIcon1");

        buttonIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/íconos/print.png"))); // NOI18N
        buttonIcon2.setText("buttonIcon2");

        javax.swing.GroupLayout panelImage2Layout = new javax.swing.GroupLayout(panelImage2);
        panelImage2.setLayout(panelImage2Layout);
        panelImage2Layout.setHorizontalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(t2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelImage2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(buttonIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImage2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelImage2Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(t15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(t14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(t13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(t12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(t9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(t10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(t11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(81, 81, 81)
                                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(t16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(t18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(t17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(t8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(buttonRound2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(panelImage2Layout.createSequentialGroup()
                                        .addComponent(buttonRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap())
                    .addGroup(panelImage2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(buttonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelImage2Layout.setVerticalGroup(
            panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImage2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImage2Layout.createSequentialGroup()
                        .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t1)
                            .addComponent(t9))
                        .addGap(28, 28, 28)
                        .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t2)
                            .addComponent(t10))
                        .addGap(30, 30, 30)
                        .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t3)
                            .addComponent(t11))
                        .addGap(18, 18, 18)
                        .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t4)
                            .addComponent(t12)))
                    .addGroup(panelImage2Layout.createSequentialGroup()
                        .addComponent(t17)
                        .addGap(28, 28, 28)
                        .addComponent(t18)
                        .addGap(18, 18, 18)
                        .addComponent(t16)
                        .addGap(18, 18, 18)
                        .addComponent(t8)))
                .addGap(7, 7, 7)
                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t5)
                    .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(t13)
                        .addComponent(buttonRound2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t14)
                    .addComponent(t6)
                    .addComponent(buttonRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(t15)
                    .addComponent(t7))
                .addGap(18, 18, 18)
                .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelImage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonIcon1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(194, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(panelImage2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSplitPane1)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
         t4.setSelected(true);
         t2.setSelected(false);
         t3.setSelected(false);
         t1.setSelected(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
         t1.setSelected(true);
         t2.setSelected(false);
         t3.setSelected(false);
         t4.setSelected(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
         t2.setSelected(true);
         t1.setSelected(false);
         t3.setSelected(false);
         t4.setSelected(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
         t3.setSelected(true);
         t2.setSelected(false);
         t1.setSelected(false);
         t4.setSelected(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void buttonRound1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRound1ActionPerformed
            String s="";
            obtenerDatos();
            objeto= new Metodos();
            s=objeto.sumatoria(matriz);
            jTextArea1.setText(s);
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRound1ActionPerformed

    private void buttonRound2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRound2ActionPerformed

        matriz = new Vector<Integer>();
        jTextArea1.setText("");
         t1.setSelected(false);
         t2.setSelected(false);
         t3.setSelected(false);
         t4.setSelected(false);
         t5.setSelected(false);
         t6.setSelected(false);
         t7.setSelected(false);
         t8.setSelected(false);
         t9.setSelected(false);
         t10.setSelected(false);
         t11.setSelected(false);
         t12.setSelected(false);
         t13.setSelected(false);
         t14.setSelected(false);
         t15.setSelected(false);
         t16.setSelected(false);
         t17.setSelected(false);
         t18.setSelected(false);
         

        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRound2ActionPerformed

    private void buttonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalirActionPerformed
        System.exit(1);
    }//GEN-LAST:event_buttonSalirActionPerformed

    /**
    * @param args the command line arguments
    */
   /** public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla_Principal().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonIcon buttonIcon1;
    private org.edisoncor.gui.button.ButtonIcon buttonIcon2;
    private org.edisoncor.gui.button.ButtonRound buttonRound1;
    private org.edisoncor.gui.button.ButtonRound buttonRound2;
    private org.edisoncor.gui.button.ButtonIcon buttonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextArea1;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    private org.edisoncor.gui.panel.PanelImage panelImage2;
    private javax.swing.JRadioButton t1;
    private javax.swing.JRadioButton t10;
    private javax.swing.JRadioButton t11;
    private javax.swing.JRadioButton t12;
    private javax.swing.JRadioButton t13;
    private javax.swing.JRadioButton t14;
    private javax.swing.JRadioButton t15;
    private javax.swing.JRadioButton t16;
    private javax.swing.JRadioButton t17;
    private javax.swing.JRadioButton t18;
    private javax.swing.JRadioButton t2;
    private javax.swing.JRadioButton t3;
    private javax.swing.JRadioButton t4;
    private javax.swing.JRadioButton t5;
    private javax.swing.JRadioButton t6;
    private javax.swing.JRadioButton t7;
    private javax.swing.JRadioButton t8;
    private javax.swing.JRadioButton t9;
    // End of variables declaration//GEN-END:variables

}
